#define BLYNK_TEMPLATE_ID "TMPL3C_DQUQrZ" //copy and paste these details generated by Blynk 
#define BLYNK_TEMPLATE_NAME "Shadow alarm notification using esp8266" //copy and paste these details generated by Blynk 
#define BLYNK_AUTH_TOKEN "MjvzH2YFz0SVJiBSGh1Jct_gtj8fZ5u_" //copy and paste these details generated by Blynk 
#define BLYNK_PRINT Serial //copy and paste these details generated by Blynk 

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

char auth[] = BLYNK_AUTH_TOKEN;
char ssid[] = ; // Type your WiFi name
char pass[] = ;       // Type your WiFi password

BlynkTimer timer;

void notifyOnTheft() {
    Serial.println(digitalRead(D8));
    if (digitalRead(D8) == HIGH) {
        Serial.println("WARNING: SHADOW DETECTED!!!");
        Blynk.logEvent("shadow_alarm", "WARNING: SHADOW DETECTED!!!"); //modify as per the requirement
        digitalWrite(D8, LOW);
    } else {
        Serial.println("No shadow...");
    }
    delay(500);
}

void setup() {
    pinMode(D8, INPUT);
    pinMode(LED_BUILTIN, OUTPUT);
    pinMode(D7, OUTPUT);
    Serial.begin(115200);
    Blynk.begin(auth, ssid, pass);
    timer.setInterval(5000L, notifyOnTheft);
}

void loop() {
    Blynk.run();
    delay(500);
    
    if (digitalRead(D8) == HIGH) {
        digitalWrite(LED_BUILTIN, HIGH);
        delay(20);
        digitalWrite(D7, HIGH);
        delay(20);
    } else {
        digitalWrite(LED_BUILTIN, LOW);
        delay(20);
        digitalWrite(D7, LOW);
        delay(20);
    }
    
    timer.run();
}
